// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Amounts
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS';
export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const TRIGGER_CART_UPDATE = 'TRIGGER_CART_UPDATE';
export const ADD_ORDER_ITEMS = 'ADD_ORDER_ITEMS';
export const REMOVE_ORDER_ITEMS = 'REMOVE_ORDER_ITEMS';
export const SET_ORDER_ITEMS = 'SET_ORDER_ITEMS';
export const ADD_LISTING_ITEMS = 'ADD_LISTING_ITEMS';
export const REMOVE_LISTING_ITEMS = 'REMOVE_LISTING_ITEMS';
export const SET_LISTING_ITEMS = 'SET_LISTING_ITEMS';
export const ADD_PENDING_ITEMS = 'ADD_PENDING_ITEMS';
export const REMOVE_PENDING_ITEMS = 'REMOVE_PENDING_ITEMS';
export const SET_PENDING_ITEMS = 'SET_PENDING_ITEMS';